# Generated by Django 3.0.4 on 2020-06-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(help_text='Enter Pincode', max_length=6),
        ),
    ]
