# Generated by Django 3.0.4 on 2020-06-12 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200612_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinstance',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Product'),
        ),
        migrations.AlterField(
            model_name='productinstance',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default='S', help_text='Book availability', max_length=2),
        ),
    ]
