# Generated by Django 3.0.4 on 2020-06-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
