# Generated by Django 3.0.4 on 2020-06-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200616_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='address',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='phone_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='price',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='size',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='pincode',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='uuid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
