# Generated by Django 3.0.4 on 2020-06-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200616_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='panchayath',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
